-- Seed SQL para Supabase/PostgreSQL com pgvector habilitado.
-- Objetivo: persistir no banco o mesmo dicionario SAP ficticio usado no projeto.
-- Observacao: este script cria a estrutura relacional completa e deixa a tabela
-- vetorial pronta para receber embeddings posteriormente.

BEGIN;

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS sap_domains (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    chart_recommendation TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sap_domain_terms (
    domain_id BIGINT NOT NULL REFERENCES sap_domains(id) ON DELETE CASCADE,
    term TEXT NOT NULL,
    PRIMARY KEY (domain_id, term)
);

CREATE TABLE IF NOT EXISTS sap_tables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    module TEXT NOT NULL,
    domain_id BIGINT NOT NULL REFERENCES sap_domains(id),
    description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sap_table_terms (
    table_id BIGINT NOT NULL REFERENCES sap_tables(id) ON DELETE CASCADE,
    term TEXT NOT NULL,
    PRIMARY KEY (table_id, term)
);

CREATE TABLE IF NOT EXISTS sap_table_join_keys (
    table_id BIGINT NOT NULL REFERENCES sap_tables(id) ON DELETE CASCADE,
    join_key TEXT NOT NULL,
    PRIMARY KEY (table_id, join_key)
);

CREATE TABLE IF NOT EXISTS sap_fields (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id BIGINT NOT NULL REFERENCES sap_tables(id) ON DELETE CASCADE,
    field_name TEXT NOT NULL,
    label TEXT NOT NULL,
    data_type TEXT NOT NULL,
    description TEXT NOT NULL,
    UNIQUE (table_id, field_name)
);

CREATE TABLE IF NOT EXISTS sap_dictionary_embeddings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key TEXT NOT NULL UNIQUE,
    source_type TEXT NOT NULL CHECK (source_type IN ('table', 'field')),
    table_name TEXT NOT NULL,
    field_name TEXT,
    module TEXT NOT NULL,
    domain_name TEXT NOT NULL,
    description TEXT NOT NULL,
    content_text TEXT NOT NULL,
    embedding VECTOR(384)
);

ALTER TABLE sap_dictionary_embeddings
    ADD COLUMN IF NOT EXISTS source_key TEXT;

UPDATE sap_dictionary_embeddings
SET source_key = CASE
    WHEN source_type = 'table' THEN CONCAT('table:', table_name)
    ELSE CONCAT('field:', table_name, '.', field_name)
END
WHERE source_key IS NULL;

ALTER TABLE sap_dictionary_embeddings
    ALTER COLUMN source_key SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_sap_tables_domain_id
    ON sap_tables (domain_id);

CREATE INDEX IF NOT EXISTS idx_sap_fields_table_id
    ON sap_fields (table_id);

CREATE INDEX IF NOT EXISTS idx_sap_embeddings_source
    ON sap_dictionary_embeddings (source_type, table_name, field_name);

CREATE UNIQUE INDEX IF NOT EXISTS idx_sap_embeddings_source_key
    ON sap_dictionary_embeddings (source_key);

INSERT INTO sap_domains (name, chart_recommendation)
VALUES
    ('producao', 'grafico de colunas por mes e planta'),
    ('faturamento', 'grafico de linhas ou colunas por mes'),
    ('compras', 'grafico de barras por fornecedor ou material'),
    ('financeiro', 'grafico de linhas ou colunas por mes e departamento')
ON CONFLICT (name) DO UPDATE
SET chart_recommendation = EXCLUDED.chart_recommendation;

INSERT INTO sap_domain_terms (domain_id, term)
SELECT d.id, v.term
FROM sap_domains d
JOIN (
    VALUES
        ('producao', 'producao'),
        ('producao', 'produzido'),
        ('producao', 'volume'),
        ('producao', 'ordem'),
        ('producao', 'planta'),
        ('producao', 'fabrica'),
        ('producao', 'mes'),
        ('producao', 'periodo'),
        ('faturamento', 'faturamento'),
        ('faturamento', 'venda'),
        ('faturamento', 'receita'),
        ('faturamento', 'nota fiscal'),
        ('faturamento', 'cliente'),
        ('faturamento', 'mes'),
        ('faturamento', 'regional'),
        ('compras', 'compra'),
        ('compras', 'fornecedor'),
        ('compras', 'pedido'),
        ('compras', 'gasto'),
        ('compras', 'valor comprado'),
        ('compras', 'material'),
        ('financeiro', 'financeiro'),
        ('financeiro', 'folha'),
        ('financeiro', 'folha de pagamento'),
        ('financeiro', 'salario'),
        ('financeiro', 'salario medio'),
        ('financeiro', 'media salarial'),
        ('financeiro', 'rendimento'),
        ('financeiro', 'beneficio'),
        ('financeiro', 'encargo'),
        ('financeiro', 'desconto'),
        ('financeiro', 'custo de pessoal'),
        ('financeiro', 'departamento'),
        ('financeiro', 'centro de custo'),
        ('financeiro', 'cargo'),
        ('financeiro', 'remuneracao'),
        ('financeiro', 'recursos humanos'),
        ('financeiro', 'rh')
) AS v(domain_name, term)
    ON d.name = v.domain_name
ON CONFLICT (domain_id, term) DO NOTHING;

INSERT INTO sap_tables (name, module, domain_id, description)
SELECT v.table_name, v.module, d.id, v.description
FROM sap_domains d
JOIN (
    VALUES
        ('AFKO', 'PP', 'producao', 'Cabecalho das ordens de producao'),
        ('AFPO', 'PP', 'producao', 'Itens da ordem de producao'),
        ('VBRK', 'SD', 'faturamento', 'Cabecalho do documento de faturamento'),
        ('VBRP', 'SD', 'faturamento', 'Itens do documento de faturamento'),
        ('EKKO', 'MM', 'compras', 'Cabecalho do pedido de compra'),
        ('EKPO', 'MM', 'compras', 'Itens do pedido de compra'),
        ('ZHR_FOLHA', 'FI-HR', 'financeiro', 'Resumo mensal agregado da folha de pagamento por departamento e cargo')
) AS v(table_name, module, domain_name, description)
    ON d.name = v.domain_name
ON CONFLICT (name) DO UPDATE
SET
    module = EXCLUDED.module,
    domain_id = EXCLUDED.domain_id,
    description = EXCLUDED.description;

INSERT INTO sap_table_terms (table_id, term)
SELECT t.id, v.term
FROM sap_tables t
JOIN (
    VALUES
        ('AFKO', 'producao'),
        ('AFKO', 'ordem'),
        ('AFKO', 'planta'),
        ('AFKO', 'volume produzido'),
        ('AFKO', 'data de inicio'),
        ('AFKO', 'quantidade planejada'),
        ('AFPO', 'material produzido'),
        ('AFPO', 'item da ordem'),
        ('AFPO', 'quantidade da ordem'),
        ('VBRK', 'faturamento'),
        ('VBRK', 'nota fiscal'),
        ('VBRK', 'cliente'),
        ('VBRK', 'receita'),
        ('VBRK', 'regional'),
        ('VBRK', 'data de faturamento'),
        ('VBRP', 'valor faturado'),
        ('VBRP', 'item faturado'),
        ('VBRP', 'material faturado'),
        ('VBRP', 'quantidade faturada'),
        ('EKKO', 'compra'),
        ('EKKO', 'pedido'),
        ('EKKO', 'fornecedor'),
        ('EKKO', 'data do pedido'),
        ('EKKO', 'grupo de compras'),
        ('EKPO', 'material comprado'),
        ('EKPO', 'valor comprado'),
        ('EKPO', 'quantidade comprada'),
        ('ZHR_FOLHA', 'folha de pagamento'),
        ('ZHR_FOLHA', 'salario'),
        ('ZHR_FOLHA', 'salario bruto'),
        ('ZHR_FOLHA', 'salario liquido'),
        ('ZHR_FOLHA', 'salario medio'),
        ('ZHR_FOLHA', 'media salarial'),
        ('ZHR_FOLHA', 'rendimento'),
        ('ZHR_FOLHA', 'beneficio'),
        ('ZHR_FOLHA', 'encargo'),
        ('ZHR_FOLHA', 'desconto'),
        ('ZHR_FOLHA', 'custo total da folha'),
        ('ZHR_FOLHA', 'departamento'),
        ('ZHR_FOLHA', 'centro de custo'),
        ('ZHR_FOLHA', 'cargo'),
        ('ZHR_FOLHA', 'remuneracao'),
        ('ZHR_FOLHA', 'recursos humanos'),
        ('ZHR_FOLHA', 'rh')
) AS v(table_name, term)
    ON t.name = v.table_name
ON CONFLICT (table_id, term) DO NOTHING;

INSERT INTO sap_table_join_keys (table_id, join_key)
SELECT t.id, v.join_key
FROM sap_tables t
JOIN (
    VALUES
        ('AFKO', 'AUFNR'),
        ('AFKO', 'WERKS'),
        ('AFPO', 'AUFNR'),
        ('AFPO', 'MATNR'),
        ('VBRK', 'VBELN'),
        ('VBRK', 'KUNNR'),
        ('VBRP', 'VBELN'),
        ('VBRP', 'MATNR'),
        ('EKKO', 'EBELN'),
        ('EKKO', 'LIFNR'),
        ('EKPO', 'EBELN'),
        ('EKPO', 'MATNR'),
        ('ZHR_FOLHA', 'KOSTL'),
        ('ZHR_FOLHA', 'DEPARTAMENTO'),
        ('ZHR_FOLHA', 'CARGO')
) AS v(table_name, join_key)
    ON t.name = v.table_name
ON CONFLICT (table_id, join_key) DO NOTHING;

INSERT INTO sap_fields (table_id, field_name, label, data_type, description)
SELECT t.id, v.field_name, v.label, v.data_type, v.description
FROM sap_tables t
JOIN (
    VALUES
        ('AFKO', 'AUFNR', 'ordem_producao', 'text', 'Numero da ordem de producao'),
        ('AFKO', 'WERKS', 'planta', 'text', 'Codigo da planta'),
        ('AFKO', 'GSTRP', 'data_inicio', 'date', 'Data de inicio da ordem'),
        ('AFKO', 'GLTRP', 'data_fim', 'date', 'Data de fim da ordem'),
        ('AFKO', 'GAMNG', 'volume_producao', 'number', 'Quantidade total planejada/produzida'),
        ('AFPO', 'AUFNR', 'ordem_producao', 'text', 'Numero da ordem de producao'),
        ('AFPO', 'MATNR', 'material', 'text', 'Codigo do material'),
        ('AFPO', 'PSMNG', 'quantidade_item', 'number', 'Quantidade prevista do item'),
        ('VBRK', 'VBELN', 'documento_faturamento', 'text', 'Numero do documento de faturamento'),
        ('VBRK', 'FKDAT', 'data_faturamento', 'date', 'Data de faturamento'),
        ('VBRK', 'KUNNR', 'cliente', 'text', 'Codigo do cliente'),
        ('VBRK', 'VKORG', 'organizacao_vendas', 'text', 'Organizacao de vendas'),
        ('VBRP', 'VBELN', 'documento_faturamento', 'text', 'Numero do documento de faturamento'),
        ('VBRP', 'MATNR', 'material', 'text', 'Codigo do material'),
        ('VBRP', 'FKIMG', 'quantidade_faturada', 'number', 'Quantidade faturada'),
        ('VBRP', 'NETWR', 'valor_faturado', 'number', 'Valor liquido do item'),
        ('EKKO', 'EBELN', 'pedido_compra', 'text', 'Numero do pedido de compra'),
        ('EKKO', 'BEDAT', 'data_pedido', 'date', 'Data do pedido'),
        ('EKKO', 'LIFNR', 'fornecedor', 'text', 'Codigo do fornecedor'),
        ('EKKO', 'EKGRP', 'grupo_compras', 'text', 'Grupo de compras'),
        ('EKPO', 'EBELN', 'pedido_compra', 'text', 'Numero do pedido de compra'),
        ('EKPO', 'MATNR', 'material', 'text', 'Codigo do material'),
        ('EKPO', 'MENGE', 'quantidade_comprada', 'number', 'Quantidade comprada'),
        ('EKPO', 'NETWR', 'valor_comprado', 'number', 'Valor liquido do item'),
        ('ZHR_FOLHA', 'DOCFOLHA', 'documento_folha', 'text', 'Identificador do resumo mensal da folha'),
        ('ZHR_FOLHA', 'COMPETENCIA', 'mes', 'date', 'Competencia mensal da folha'),
        ('ZHR_FOLHA', 'KOSTL', 'centro_custo', 'text', 'Centro de custo responsavel pela despesa de pessoal'),
        ('ZHR_FOLHA', 'DEPARTAMENTO', 'departamento', 'text', 'Departamento consolidado da folha'),
        ('ZHR_FOLHA', 'CARGO', 'cargo', 'text', 'Cargo ou familia de cargos'),
        ('ZHR_FOLHA', 'QTD_FUNC', 'quantidade_funcionarios', 'number', 'Quantidade de funcionarios no grupo'),
        ('ZHR_FOLHA', 'SAL_BASE', 'salario_base', 'number', 'Soma do salario base'),
        ('ZHR_FOLHA', 'REND_TOTAL', 'rendimento_total', 'number', 'Soma dos rendimentos brutos'),
        ('ZHR_FOLHA', 'BENEFICIOS', 'beneficios', 'number', 'Valor total de beneficios'),
        ('ZHR_FOLHA', 'DESCONTOS', 'descontos', 'number', 'Valor total de descontos'),
        ('ZHR_FOLHA', 'ENCARGOS', 'encargos', 'number', 'Encargos patronais estimados'),
        ('ZHR_FOLHA', 'SAL_LIQUIDO', 'salario_liquido', 'number', 'Valor liquido pago aos funcionarios'),
        ('ZHR_FOLHA', 'CUSTO_TOTAL', 'custo_total_folha', 'number', 'Custo total da folha incluindo rendimentos, beneficios e encargos')
) AS v(table_name, field_name, label, data_type, description)
    ON t.name = v.table_name
ON CONFLICT (table_id, field_name) DO UPDATE
SET
    label = EXCLUDED.label,
    data_type = EXCLUDED.data_type,
    description = EXCLUDED.description;

INSERT INTO sap_dictionary_embeddings (
    source_key,
    source_type,
    table_name,
    field_name,
    module,
    domain_name,
    description,
    content_text,
    embedding
)
SELECT
    CONCAT('table:', t.name) AS source_key,
    'table' AS source_type,
    t.name AS table_name,
    NULL AS field_name,
    t.module,
    d.name AS domain_name,
    t.description,
    CONCAT(
        'Tabela SAP ', t.name,
        ' do modulo ', t.module,
        '. Dominio: ', d.name,
        '. Descricao: ', t.description
    ) AS content_text,
    NULL AS embedding
FROM sap_tables t
JOIN sap_domains d ON d.id = t.domain_id
ON CONFLICT (source_key) DO UPDATE
SET
    source_type = EXCLUDED.source_type,
    table_name = EXCLUDED.table_name,
    field_name = EXCLUDED.field_name,
    module = EXCLUDED.module,
    domain_name = EXCLUDED.domain_name,
    description = EXCLUDED.description,
    content_text = EXCLUDED.content_text,
    embedding = CASE
        WHEN sap_dictionary_embeddings.content_text IS DISTINCT FROM EXCLUDED.content_text
            THEN NULL
        ELSE sap_dictionary_embeddings.embedding
    END;

INSERT INTO sap_dictionary_embeddings (
    source_key,
    source_type,
    table_name,
    field_name,
    module,
    domain_name,
    description,
    content_text,
    embedding
)
SELECT
    CONCAT('field:', t.name, '.', f.field_name) AS source_key,
    'field' AS source_type,
    t.name AS table_name,
    f.field_name,
    t.module,
    d.name AS domain_name,
    f.description,
    CONCAT(
        'Campo ', t.name, '.', f.field_name,
        ' com label ', f.label,
        '. Tipo: ', f.data_type,
        '. Descricao: ', f.description,
        '. Dominio: ', d.name
    ) AS content_text,
    NULL AS embedding
FROM sap_fields f
JOIN sap_tables t ON t.id = f.table_id
JOIN sap_domains d ON d.id = t.domain_id
ON CONFLICT (source_key) DO UPDATE
SET
    source_type = EXCLUDED.source_type,
    table_name = EXCLUDED.table_name,
    field_name = EXCLUDED.field_name,
    module = EXCLUDED.module,
    domain_name = EXCLUDED.domain_name,
    description = EXCLUDED.description,
    content_text = EXCLUDED.content_text,
    embedding = CASE
        WHEN sap_dictionary_embeddings.content_text IS DISTINCT FROM EXCLUDED.content_text
            THEN NULL
        ELSE sap_dictionary_embeddings.embedding
    END;

CREATE INDEX IF NOT EXISTS idx_sap_embeddings_vector_cosine
    ON sap_dictionary_embeddings
    USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 10);

CREATE OR REPLACE FUNCTION match_sap_dictionary_embeddings(
    query_embedding VECTOR(384),
    match_count INTEGER DEFAULT 10,
    filter_source_type TEXT DEFAULT NULL,
    filter_domain_name TEXT DEFAULT NULL,
    filter_module TEXT DEFAULT NULL
)
RETURNS TABLE (
    source_key TEXT,
    source_type TEXT,
    table_name TEXT,
    field_name TEXT,
    module TEXT,
    domain_name TEXT,
    description TEXT,
    content_text TEXT,
    similarity DOUBLE PRECISION
)
LANGUAGE SQL
AS $$
    SELECT
        e.source_key,
        e.source_type,
        e.table_name,
        e.field_name,
        e.module,
        e.domain_name,
        e.description,
        e.content_text,
        1 - (e.embedding <=> query_embedding) AS similarity
    FROM sap_dictionary_embeddings e
    WHERE e.embedding IS NOT NULL
      AND (filter_source_type IS NULL OR e.source_type = filter_source_type)
      AND (filter_domain_name IS NULL OR e.domain_name = filter_domain_name)
      AND (filter_module IS NULL OR e.module = filter_module)
    ORDER BY e.embedding <=> query_embedding
    LIMIT match_count;
$$;

COMMIT;

-- Consultas uteis de verificacao:
-- SELECT * FROM sap_domains;
-- SELECT t.name, t.module, d.name AS domain_name FROM sap_tables t JOIN sap_domains d ON d.id = t.domain_id;
-- SELECT table_name, field_name, source_type, embedding IS NULL AS embedding_pendente FROM sap_dictionary_embeddings;
