-- Seed SQL parametrizado para dados transacionais ficticios SAP.
-- Objetivo:
-- 1. Popular o banco com um volume maior de dados para producao, faturamento e compras.
-- 2. Criar historico suficiente para consultas por qualquer quantidade de meses dentro da janela gerada.
-- 3. Incluir sazonalidade, lacunas de movimento e joins mais ricos entre cabecalho e itens.

BEGIN;

CREATE TABLE IF NOT EXISTS afko (
    aufnr TEXT PRIMARY KEY,
    werks TEXT NOT NULL,
    gstrp DATE NOT NULL,
    gltrp DATE NOT NULL,
    gamng NUMERIC(14, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS afpo (
    aufnr TEXT NOT NULL,
    matnr TEXT NOT NULL,
    psmng NUMERIC(14, 2) NOT NULL,
    PRIMARY KEY (aufnr, matnr)
);

CREATE TABLE IF NOT EXISTS vbrk (
    vbeln TEXT PRIMARY KEY,
    fkdat DATE NOT NULL,
    kunnr TEXT NOT NULL,
    vkorg TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS vbrp (
    vbeln TEXT NOT NULL,
    matnr TEXT NOT NULL,
    fkimg NUMERIC(14, 2) NOT NULL,
    netwr NUMERIC(14, 2) NOT NULL,
    PRIMARY KEY (vbeln, matnr)
);

CREATE TABLE IF NOT EXISTS ekko (
    ebeln TEXT PRIMARY KEY,
    bedat DATE NOT NULL,
    lifnr TEXT NOT NULL,
    ekgrp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ekpo (
    ebeln TEXT NOT NULL,
    matnr TEXT NOT NULL,
    menge NUMERIC(14, 2) NOT NULL,
    netwr NUMERIC(14, 2) NOT NULL,
    PRIMARY KEY (ebeln, matnr)
);

CREATE TABLE IF NOT EXISTS script_query_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    requested_by TEXT NOT NULL,
    question TEXT NOT NULL,
    generated_sql TEXT NOT NULL,
    retrieval_mode TEXT NOT NULL,
    execution_status TEXT NOT NULL,
    row_count INTEGER NOT NULL DEFAULT 0,
    result_preview JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_script_query_history_user_id
    ON script_query_history (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_script_query_history_requested_by
    ON script_query_history (requested_by, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_afko_gstrp_werks
    ON afko (gstrp, werks);

CREATE INDEX IF NOT EXISTS idx_afpo_matnr
    ON afpo (matnr);

CREATE INDEX IF NOT EXISTS idx_vbrk_fkdat_kunnr
    ON vbrk (fkdat, kunnr);

CREATE INDEX IF NOT EXISTS idx_vbrk_vkorg
    ON vbrk (vkorg);

CREATE INDEX IF NOT EXISTS idx_vbrp_matnr
    ON vbrp (matnr);

CREATE INDEX IF NOT EXISTS idx_ekko_bedat_lifnr
    ON ekko (bedat, lifnr);

CREATE INDEX IF NOT EXISTS idx_ekko_ekgrp
    ON ekko (ekgrp);

CREATE INDEX IF NOT EXISTS idx_ekpo_matnr
    ON ekpo (matnr);

TRUNCATE TABLE afpo, afko, vbrp, vbrk, ekpo, ekko;

DO $$
DECLARE
    history_months INTEGER := 36;
    start_month DATE := (DATE_TRUNC('month', CURRENT_DATE) - MAKE_INTERVAL(months => history_months))::date;
    plants TEXT[] := ARRAY['PL01', 'PL02', 'PL03', 'PL04', 'PL05'];
    clients TEXT[] := ARRAY['CLI-001', 'CLI-002', 'CLI-003', 'CLI-004', 'CLI-005', 'CLI-006', 'CLI-007', 'CLI-008', 'CLI-009', 'CLI-010'];
    client_regions TEXT[] := ARRAY['SUL', 'SUDESTE', 'NORDESTE', 'NORTE', 'CENTRO-OESTE', 'SUL', 'SUDESTE', 'NORDESTE', 'NORTE', 'CENTRO-OESTE'];
    suppliers TEXT[] := ARRAY['FOR-001', 'FOR-002', 'FOR-003', 'FOR-004', 'FOR-005', 'FOR-006', 'FOR-007'];
    purchase_groups TEXT[] := ARRAY['GRP-A', 'GRP-B', 'GRP-C', 'GRP-D'];
    materials TEXT[] := ARRAY['MAT-100', 'MAT-101', 'MAT-102', 'MAT-103', 'MAT-104', 'MAT-105', 'MAT-106', 'MAT-107', 'MAT-108', 'MAT-109', 'MAT-110', 'MAT-111'];
    seasonality NUMERIC[] := ARRAY[1.16, 0.94, 1.01, 1.08, 1.04, 1.12, 0.96, 0.91, 1.02, 1.07, 1.18, 1.28];
    order_seq BIGINT := 1000000;
    invoice_seq BIGINT := 900000;
    purchase_seq BIGINT := 4500000;
    month_offset INTEGER;
    month_start DATE;
    month_factor NUMERIC;
    plant_idx INTEGER;
    client_idx INTEGER;
    supplier_idx INTEGER;
    order_loop INTEGER;
    invoice_loop INTEGER;
    purchase_loop INTEGER;
    line_idx INTEGER;
    line_count INTEGER;
    order_id TEXT;
    invoice_id TEXT;
    purchase_id TEXT;
    start_date DATE;
    end_date DATE;
    volume NUMERIC;
    quantity NUMERIC;
    amount NUMERIC;
    item_share NUMERIC;
    material_code TEXT;
    region_code TEXT;
BEGIN
    FOR month_offset IN 0..history_months - 1 LOOP
        month_start := (start_month + MAKE_INTERVAL(months => month_offset))::date;
        month_factor := seasonality[EXTRACT(MONTH FROM month_start)::INTEGER];

        -- Producao: varios pedidos por planta, com alguns meses sem movimento em plantas especificas.
        FOR plant_idx IN 1..array_length(plants, 1) LOOP
            IF (plant_idx = 5 AND EXTRACT(MONTH FROM month_start)::INTEGER IN (2, 7, 11))
               OR (plant_idx = 4 AND month_offset % 6 = 0) THEN
                CONTINUE;
            END IF;

            FOR order_loop IN 1..(2 + ((month_offset + plant_idx) % 3)) LOOP
                order_seq := order_seq + 1;
                order_id := order_seq::TEXT;
                start_date := month_start + (((plant_idx * 3 + order_loop * 5 + month_offset) % 22))::INTEGER;
                end_date := start_date + (2 + ((plant_idx + order_loop + month_offset) % 5));
                volume := ROUND(
                    (
                        (920 + plant_idx * 145 + order_loop * 60)
                        * month_factor
                        * (1 + ((month_offset % 4) * 0.03))
                    )::NUMERIC,
                    2
                );

                INSERT INTO afko (aufnr, werks, gstrp, gltrp, gamng)
                VALUES (order_id, plants[plant_idx], start_date, end_date, volume);

                line_count := 2 + ((order_loop + month_offset) % 2);
                FOR line_idx IN 1..line_count LOOP
                    material_code := materials[((month_offset + plant_idx + line_idx - 1) % array_length(materials, 1)) + 1];
                    item_share := 0.28 + line_idx * 0.17;

                    INSERT INTO afpo (aufnr, matnr, psmng)
                    VALUES (
                        order_id,
                        material_code,
                        ROUND((volume * item_share)::NUMERIC, 2)
                    );
                END LOOP;
            END LOOP;
        END LOOP;

        -- Faturamento: mais clientes, mais regionais, sazonalidade e lacunas de movimento em algumas series.
        FOR client_idx IN 1..array_length(clients, 1) LOOP
            region_code := client_regions[client_idx];

            IF (region_code = 'NORTE' AND EXTRACT(MONTH FROM month_start)::INTEGER IN (3, 9))
               OR (client_idx IN (3, 8) AND month_offset % 5 = 0) THEN
                CONTINUE;
            END IF;

            FOR invoice_loop IN 1..(1 + ((month_offset + client_idx) % 3)) LOOP
                invoice_seq := invoice_seq + 1;
                invoice_id := invoice_seq::TEXT;

                INSERT INTO vbrk (vbeln, fkdat, kunnr, vkorg)
                VALUES (
                    invoice_id,
                    month_start + (((client_idx * 2 + invoice_loop * 4 + month_offset) % 25))::INTEGER,
                    clients[client_idx],
                    region_code
                );

                line_count := 1 + ((invoice_loop + client_idx + month_offset) % 3);
                FOR line_idx IN 1..line_count LOOP
                    material_code := materials[((client_idx + month_offset + line_idx * 2 - 1) % array_length(materials, 1)) + 1];
                    quantity := ROUND(
                        (
                            (45 + client_idx * 11 + line_idx * 14 + (month_offset % 6) * 7)
                            * month_factor
                        )::NUMERIC,
                        2
                    );
                    amount := ROUND(
                        (
                            quantity
                            * (58 + ((client_idx + line_idx) % 5) * 11)
                            * (1 + ((EXTRACT(MONTH FROM month_start)::INTEGER % 4) * 0.02))
                        )::NUMERIC,
                        2
                    );

                    INSERT INTO vbrp (vbeln, matnr, fkimg, netwr)
                    VALUES (invoice_id, material_code, quantity, amount);
                END LOOP;
            END LOOP;
        END LOOP;

        -- Compras: mais fornecedores, grupos de compra e itens por pedido, com meses sem movimento para algumas series.
        FOR supplier_idx IN 1..array_length(suppliers, 1) LOOP
            IF (supplier_idx = 6 AND EXTRACT(MONTH FROM month_start)::INTEGER IN (1, 6, 12))
               OR (supplier_idx = 7 AND month_offset % 4 = 0) THEN
                CONTINUE;
            END IF;

            FOR purchase_loop IN 1..(1 + ((supplier_idx + month_offset) % 2)) LOOP
                purchase_seq := purchase_seq + 1;
                purchase_id := purchase_seq::TEXT;

                INSERT INTO ekko (ebeln, bedat, lifnr, ekgrp)
                VALUES (
                    purchase_id,
                    month_start + (((supplier_idx * 3 + purchase_loop * 5 + month_offset) % 24))::INTEGER,
                    suppliers[supplier_idx],
                    purchase_groups[((supplier_idx + purchase_loop + month_offset - 1) % array_length(purchase_groups, 1)) + 1]
                );

                line_count := 2 + ((supplier_idx + purchase_loop + month_offset) % 2);
                FOR line_idx IN 1..line_count LOOP
                    material_code := materials[((supplier_idx + month_offset + line_idx - 1) % array_length(materials, 1)) + 1];
                    quantity := ROUND(
                        (
                            (140 + supplier_idx * 35 + line_idx * 26 + (month_offset % 5) * 18)
                            * (month_factor * 0.92)
                        )::NUMERIC,
                        2
                    );
                    amount := ROUND(
                        (
                            quantity
                            * (22 + ((supplier_idx + line_idx) % 6) * 4)
                            * (1 + ((month_offset % 3) * 0.015))
                        )::NUMERIC,
                        2
                    );

                    INSERT INTO ekpo (ebeln, matnr, menge, netwr)
                    VALUES (purchase_id, material_code, quantity, amount);
                END LOOP;
            END LOOP;
        END LOOP;
    END LOOP;
END $$;

COMMIT;

-- Consultas uteis:
-- SELECT requested_by, question, execution_status, row_count, created_at FROM script_query_history ORDER BY created_at DESC;
-- SELECT COUNT(*) FROM vbrk;
-- SELECT DATE_TRUNC('month', fkdat) AS mes, COUNT(*) FROM vbrk GROUP BY 1 ORDER BY 1;
